Added more logical error handling
phpMv/ubiquity pull request #197
Opened 2022-09-15 13:42 UTC by pifagor87

# Description
For some reason, getTraceAsString is used as the error message. It is wrong. After all, we have to use getMessage

## Type of change
Bug fixes and bug-level categorization added

# How Has This Been Tested?
Make a critical error on the site and check the error correction

2022-09-16 06:29 UTC, jcheron commented
Thanks @pifagor87 
I solve the test problem, and look at this.

2022-09-16 22:38 UTC, jcheron requested changes
Hi @pifagor87 
The `runAction` method is already too long (Sonar says so).
It would probably be better to relocate your changes to a static method `logError(int $code,string $message)`

which could also be called in the `runAction` method of the `StartupAsync` class which has the same need.

2022-10-20 15:42 UTC, pifagor87 commented
Hello @jcheron 

Thanks for the recommendations. Made the necessary changes.

Kind regards,
Oleksandr

2022-10-20 17:39 UTC, jcheron approved these changes
Thanks @pifagor87 
Great!
I may pass the **logError** method as protected, since it doesn't need to be accessible from outside.

Thanks again for your contribution!

2022-10-20 17:39 UTC, merged